sudo: required
dist: trusty
addons:
    chrome: stable
language: node_js
node_js:
    - '11'
before_install:
    - npm i npm@^6 -g
    - npm install -g @angular/cli
install:
    - npm install
script:
    - npm run test-lib-ci
    - npm run build-lib
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
after_success:
    - cd ../..
    - ls
    - ng new testProject
    - cd ./testProject
    - npm install ../damienbod/angular-auth-oidc-client/dist/angular-auth-oidc-client
    - npm test -- --watch=false --browsers=ChromeHeadless
notifications:
    email: false
